### PR TITLE
Strict Semver Validation 

### LINKED ISSUE #4: Semver Validation Does Not Comply With Spec
When parsing strings as semver with ```[SWFSemanticVersion semanticVersionWithString]```, the library fails to follow Paragraph 2 of the spec: 

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. http://semver.org/#spec-item-2

The following should fail validation, but passes:

```
1  # missing minor and patch
1.0 # missing patch
1.0.003 # contain leading zeroes.
```

### PR DESCRIPTION
**Pull request by jonmchan**
Fixes #4 - make library comply with http://semver.org/#spec-item-2 of semver spec.

### CODE REVIEW

**Comment by samuelwford** [comment]
I like the fix - any reason not to make it just the normal parsing behavior (instead of a strict option)?

**Comment by wlisac** [comment]
@samuelwford I'm certainly to blame for some of this forgiving parsing – https://github.com/samuelwford/SWFSemanticVersion/pull/2

I like making strict the default, but I'd certainly still appreciate an option to initialize with a forgiving parser.

**Comment by jonmchan** [comment]
I only made it forgiving by default to not break any current behavior. I'm a firm believer to not release libraries that break software and a change like this certainly is a breaking change! Anyone who is currently using versions like 1.0 and 2 expecting it to parse to 1.0.0 and 2.0.0 no longer will work after this change. 

Project owner's call though - I just started using the library so I don't have a vested interest in either way.

Want me to make it strict by default?

**Comment by samuelwford** [comment]
Thanks for the PR!

I merged & published version 0.5.0 of the pod.

**Pull request merged**
